version: '3.8'

services:
  app:
    build:
      dockerfile: ./dockerfiles/python/Dockerfile
    container_name: auth-base_app
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8000:8000"
    tty: true
